export interface PlanetsDto
{
    id:string,
    name:string,
    rotation_period:string,
    orbital_period:string,
    diameter:string,
    climate:string,
    gravity:string
}
export const dummyPlanetsData: PlanetsDto[] = [
    {
      id: '1',
      name: 'Mercury',
      rotation_period: '58.6 days',
      orbital_period: '88 days',
      diameter: '4879 km',
      climate: 'None',
      gravity: '3.7 m/s²',
    },
    {
      id: '2',
      name: 'Venus',
      rotation_period: '243 days',
      orbital_period: '225 days',
      diameter: '12104 km',
      climate: 'Hot',
      gravity: '8.87 m/s²',
    },
    {
      id: '3',
      name: 'Earth',
      rotation_period: '24 hours',
      orbital_period: '365.25 days',
      diameter: '12742 km',
      climate: 'Varied',
      gravity: '9.81 m/s²',
    },
    {
      id: '4',
      name: 'Mars',
      rotation_period: '24.6 hours',
      orbital_period: '687 days',
      diameter: '6779 km',
      climate: 'Cold',
      gravity: '3.71 m/s²',
    },
    {
      id: '5',
      name: 'Jupiter',
      rotation_period: '9.9 hours',
      orbital_period: '12 years',
      diameter: '139820 km',
      climate: 'Gas Giant',
      gravity: '24.79 m/s²',
    },
    {
      id: '6',
      name: 'Saturn',
      rotation_period: '10.7 hours',
      orbital_period: '29 years',
      diameter: '116460 km',
      climate: 'Gas Giant',
      gravity: '10.44 m/s²',
    },
    {
      id: '7',
      name: 'Uranus',
      rotation_period: '17.2 hours',
      orbital_period: '84 years',
      diameter: '50724 km',
      climate: 'Gas Giant',
      gravity: '8.69 m/s²',
    },
    {
      id: '8',
      name: 'Neptune',
      rotation_period: '16.1 hours',
      orbital_period: '165 years',
      diameter: '49244 km',
      climate: 'Gas Giant',
      gravity: '11.15 m/s²',
    },
  ];
